### PR TITLE
create issue_template.md

### PR DESCRIPTION
**Pull request by hawa-bah**
I have just created the issue template. Let me know what you think! any suggestions of things that should be added or modified are welcome.

### CODE REVIEW

**Review by AffirmedVisionary — APPROVED** [review]
Amazingly thorough template, Wouldn't have known where to start. Well done. Happy to approve.

**Comment by lbrowncoder** [comment]
This is really good Hawa. The only thing I would add is a space to put the persons name who is reporting the issue or a space for the person who is fixing the issue.

**Review by iesea — APPROVED** [review]
Brilliant- all done @AffirmedVisionary i see these same check boxes - I was wondering how to use these @hawa-bah but Charlene did say one would just put an x in the box- great job

**Review by EbonyChantelle — APPROVED** [review]
Amazing Hawa!

**Review by tanyapowell — APPROVED** [review]
This is amazing @hawa-bah ❤️. Really thorough 😄 
Just took a quick look in #12 #16 #13 and at the moment all our documents will be in 3 separate locations once they are all merged in.

- This doc will be in the root folder
- #12 #16 will be in a `doc/` folder
- #13 will be in a `docs/` folder

I'd suggest all the documents are in a folder eventually. This is still fine to merge and we can move into a folder after. 

Great work and congrats on your first PR 🎉

**Review by Edenlsw — APPROVED** [review]
This is really good Hawa.

**Comment by SamsterB** [comment]
This looks good Hawa! Well done!

**Review by SamsterB — COMMENTED** [review]
This looks really good Hawa!

**Comment by hawa-bah** [comment]
Sure! it's a great idea to keep it more organised @lbrowncoder . I think that people will be able to assign themselves the issue and see who has submitted it from the issues tab.

**Comment by hawa-bah** [comment]
Thanks! I agree @tanyapowell. Once that I merge this branch, I will put it in the `docs/` folder since #13 has already been merged.

**Pull request merged**
