### PR TITLE
Structure 

### PR DESCRIPTION
**Pull request by AffirmedVisionary**
- [ x ] Added the H1
- [ x ] Created A logo
- [ x ] Created a favicon
- [ x ] Added favicon and logo to app
- [ x ] Moved app into the root folder

issues #9 & #10

### CODE REVIEW

**Review by EbonyChantelle — COMMENTED** [review]
Hey @AffirmedVisionary!  I have not gone through the code yet, but have done a structure comparison with #10.  Have you got README.md, node_modules, package.json and .gitignore at the top of the root before public and src?  They still show at the bottom in the repo, along with package-lock.json which I am not sure if that is something we need.  Also, did we come to a conclusion on reportWebVitals.js and serviceWorker.js?  I cannot remember.

**Review by EbonyChantelle — COMMENTED** [review]
Just gone through the code in regards to #9, everything thing looks good to me.  Though maybe someone else could review incase I missed something....

**Comment by EbonyChantelle** [comment]
Plus....great work on the logo and favicon....looks amazing!

**Comment by AffirmedVisionary** [comment]
> Hey @AffirmedVisionary! I have not gone through the code yet, but have done a structure comparison with #10. Have you got README.md, node_modules, package.json and .gitignore at the top of the root before public and src? They still show at the bottom in the repo (UNLESS I AM LOOKING IN THE WRONG PLACE), along with package-lock.json which I am not sure if that is something we need. Also, did we come to a conclusion on reportWebVitals.js and serviceWorker.js? I cannot remember.

In every repository, I have seen and even on my desktop, folders are usually above files. for example...
image


The package-lock.json, if I remember is used to store information on dependencies and I think it is needed.

**Comment by AffirmedVisionary** [comment]
> Plus....great work on the logo and favicon....looks amazing!

Thank you x

rest-rev-logo512

**Comment by EbonyChantelle** [comment]
> > Hey @AffirmedVisionary! I have not gone through the code yet, but have done a structure comparison with #10. Have you got README.md, node_modules, package.json and .gitignore at the top of the root before public and src? They still show at the bottom in the repo (UNLESS I AM LOOKING IN THE WRONG PLACE), along with package-lock.json which I am not sure if that is something we need. Also, did we come to a conclusion on reportWebVitals.js and serviceWorker.js? I cannot remember.
> 
> In every repository, I have seen and even on my desktop, folders are usually above files. for example...
> image
> 
> The package-lock.json, if I remember is used to store information on dependencies and I think it is needed.

Even if the files I mentioned are at the top of the structure in VSC?  As I cannot see that, or do not know where I can see that with the changes being merge....

And, oh okay on the pl.json.

**Comment by AffirmedVisionary** [comment]
in regards to file structure @EbonyChantelle think I may have confused myself.

in the repo it looks like

image

and in vscode it looks like

image

I still always see root files below the folders in vscode. unless it is different on a mac.

**Comment by AffirmedVisionary** [comment]
Maybe the way indentation works in markdown files it looks neater the way @tanyapowell wrote out the structure.

**Comment by EbonyChantelle** [comment]
Or maybe I am confusing you @AffirmedVisionary you (and myself) lol.  I am going from what is shown in the issue as per the attached image.  I took it that those files have to be at the top, if that makes sense....

ABE4F2DA-58FB-4343-B038-5DC7BE62758F

**Comment by AffirmedVisionary** [comment]
Okay, @EbonyChantelle that image just shows that readme, node_modules, package.json, .gitignore, public and src all need to be in the root of the repository which they now are. 

Must be just a representation since the files are not in alphabetical order, so would never look like that and I have been trying to find a repository that has files above folders and can't yet. It's the restrictions of markdown language I think.

**Comment by EbonyChantelle** [comment]
I must have ocd or something then @AffirmedVisionary as in my head, that’s how it should look lol.  And I do not even know why I am saying “I think” I have ocd, when “I know” I do lol, and with lots of things.  I get on my own damn nerves sometimes, never mind other people’s.  Anyway, I am happy to approve, though do still think it would be good if at least one other person could look over the actual code as well.

**Comment by tanyapowell** [comment]
@EbonyChantelle if you are happy with the changes feel free to "approve" and another contributor can also review 😄

**Review by EbonyChantelle — APPROVED** [review]
Seems all good to me.

**Pull request merged**
