### PR TITLE
create-react-app task completed

### PR DESCRIPTION
**Pull request by AffirmedVisionary**
instead of the serviceWorker.js it has reportWebVitals.js

if anyone has thoughts on if it is an updated version, or if one is better than the other. I ran create-react-app multiple times and the same thing happened.

ps. I will do better with naming branches. I originally thought to give myself a branch to complete all my tasks however a branch per task definitely makes more sense.

### CODE REVIEW

**Review by EbonyChantelle — COMMENTED** [review]
Everything seems to be in order, other than maybe deleting the code from the App and Index files that is not relevant to what we are doing.

Is the README that was created with the app different what I have assigned myself to work on?  As I created created a README text file for review.  Nothing in it yet, though this is following on from last night's post in our channel.

In terms of the Service Worker and Report Web Vitals, I do not really understand what they do to be honest.  Though from a quick search on Google, SW seems to be for offline experiences such as background sync and push notification, and RWV seems to be for measuring and analyising app performance.  Not sure what difference it would make to our app.  Though remember when we initially created our mybookcase app, we were asked to delete all files from the src folder apart from App.js and Index.js, then create three new folders; components, models and pages.

Your thoughts?

**Comment by AffirmedVisionary** [comment]
Okay, I can fix up those files. 

- both readme files are empty so once this task is done and merged, I assume the readme you create will be merged into it.

**Comment by jamilazd** [comment]
Looks all good Charlene, I think I have moved this to reviewer approved on my end, hopefully I have selected the right thing to enable this. As for Service Worker and Report Web Vitals, I have found some articles so I can read up on this.

**Comment by tanyapowell** [comment]
Hey @jamilazd 👋🏾 , if you're happy with this PR feel free to approve it. Then @AffirmedVisionary can merge in the first pull request of the project 🥳 

@EbonyChantelle can you open a new issue so the below can be addressed:
> other than maybe deleting the code from the App and Index files that is not relevant to what we are doing.

Someone else can then pick it up and the team work can continue 💪🏾

**Review by jamilazd — APPROVED** [review]
I have reviewed the create-react-app task and this and it all looks good.

**Pull request merged**
